### ISSUE TITLE
coc-mypy vs coc-pyright

### ISSUE THREAD

**Issue by laoshaw** [yaegassy/coc-mypy#4]
how they are related? do I need use both, or one of them? Thanks.

**Comment by yaegassy** [comment]
Hi, please use [coc-pyright](https://github.com/fannheyward/coc-pyright), which is normally maintained by @fannheyward. `coc-mypy` merely enables the language server that comes bundled with `vscode-mypy` to run on `coc.nvim`.

The advantage of `coc-mypy` is that it allows mypy to run in daemon mode.
